# permissions for end users to view rqliteclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rqlitecluster-viewer-role
rules:
- apiGroups:
  - rqlite.rqlite.fnetworks.tf
  resources:
  - rqliteclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rqlite.rqlite.fnetworks.tf
  resources:
  - rqliteclusters/status
  verbs:
  - get
